const RECRUITMENT_STAGES = {
  OA_COMPLETED: 2,
  FIRST_ROUND: 4,
  INTERVIEW_SHORTLIST: 6,
  INTERNSHIP_OFFER: 10,
  COMPLETED_INTERNSHIP: 15,
  PPO_PPI: 20,
};

const STARTUP_STAGES = {
  STARTUP_SHORTLIST: 3,
  PRE_INCUBATION: 5,
  RECOGNISED_INCUBATOR: 8,
  REGISTERED_FOUNDER: 10,
  RECOGNITION_GRANT: 15,
  FUNDING_AWARD: 20,
};

const VALID_TRACKS = ['RECRUITMENT', 'STARTUP'];

const ALL_STAGES = { ...RECRUITMENT_STAGES, ...STARTUP_STAGES };

function getStagesForTrack(track) {
  return track === 'STARTUP' ? STARTUP_STAGES : RECRUITMENT_STAGES;
}

module.exports = {
  RECRUITMENT_STAGES,
  STARTUP_STAGES,
  VALID_TRACKS,
  ALL_STAGES,
  getStagesForTrack,
};
